apiVersion: v1
kind: Service
metadata:
  name: ingaia-frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ingaia-ui-pod
    tier: frontend